### PR TITLE
Change url of production api to use https

### PR DESCRIPTION
**Pull request by ChristianLapinig**
Switched the baseURL in api.js to use `https` URL of the production AWS instance of our API backend

### CODE REVIEW

**Comment by ChristianLapinig** [comment]
@digitaluniverse Heads up, I'm getting errors on in production when trying to login or register a user.
Screen Shot 2020-04-22 at 5 37 10 PM

**Comment by XZ7QN0** [comment]
@pv-gitjob Can you check to see what certificate errors are showing up from the AWS instance?

**Comment by pv-gitjob** [comment]
Can't use aws default domain to get a proper cert, use this instead,
https://praveenv.org/

**Comment by ChristianLapinig** [comment]
Everything looks good to me. Thanks, @pv-gitjob! @jorgesv16, @digitaluniverse, or @leoskips34 please review and merge if it looks good to you

**Pull request merged**
